name: Create/update tag
on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:
    inputs:
      android:
        description: 'Whether to trigger an Android build (true/false/auto)'
        required: false
        default: 'true'
     
jobs:
  syncro:
    runs-on: ubuntu-latest
    environment: Android9
    name: Sync latest commits from upstream repo
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: main
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: SolDev69/unified-mesa-project
        upstream_pull_args: '-s recursive -Xtheirs'
        target_branch_push_args: --force
        test_mode: false 
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}
    outputs: 
      isUpdated: ${{ steps.sync.outputs.has_new_commits }}
      
  create-tag:
    runs-on: ubuntu-latest
    environment: Android9
    needs: [syncro]
    if: ${{ needs.syncro.outputs.isUpdated == 'true' || github.event.inputs.android == 'true' }}
    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          fallback: 159
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.MY_TOKEN }}"
          tag: ${{ steps.semvers.outputs.patch }}

          jobs:
  mirror:
    runs-on: ubuntu-latest
    
    permissions: write-all

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clone GitLab repo
      run: git clone --branch main https://gitlab.freedesktop.org/mesa/mesa.git mirror

    - name: Copy GitHub Action file to cloned repo
      run: |
        mkdir -p mirror/.github/workflows/
        cp .github/workflows/mirror.yml mirror/.github/workflows/

    - name: Commit and force push to GitHub
      run: |
        cd mirror
        git remote set-url origin https://github.com/${{ github.repository }}.git
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Add GitHub Action file"

    - name: Push changes
      uses: ad-m/github-push-action@master
      force: true
        tags: true
